package ru.wolfram.common.presentation.test

object NodeTags {
    const val GATEWAY_SCREEN_USERNAME_TEXT_FIELD = "GATEWAY_SCREEN_USERNAME_TEXT_FIELD"
    const val GATEWAY_SCREEN_ENTER_BUTTON = "GATEWAY_SCREEN_ENTER_TEXT_FIELD"
    const val GATEWAY_SCREEN_REGISTER_BUTTON = "GATEWAY_SCREEN_REGISTER_BUTTON"
    const val REGISTRATION_FOR_EMAIL_CODE_USERNAME_TEXT_FIELD =
        "REGISTRATION_FOR_EMAIL_CODE_USERNAME_TEXT_FIELD"
    const val REGISTRATION_FOR_EMAIL_CODE_PASSWORD_TEXT_FIELD =
        "REGISTRATION_FOR_EMAIL_CODE_PASSWORD_TEXT_FIELD"
    const val REGISTRATION_FOR_EMAIL_CODE_EMAIL_TEXT_FIELD =
        "REGISTRATION_FOR_EMAIL_CODE_EMAIL_TEXT_FIELD"
    const val REGISTRATION_FOR_EMAIL_CODE_REGISTER_BUTTON =
        "REGISTRATION_FOR_EMAIL_CODE_REGISTER_BUTTON"
    const val REGISTRATION_WITH_EMAIL_CODE_CODE_TEXT_FIELD =
        "REGISTRATION_WITH_EMAIL_CODE_CODE_TEXT_FIELD"
    const val REGISTRATION_WITH_EMAIL_CODE_CONFIRM_BUTTON =
        "REGISTRATION_WITH_EMAIL_CODE_CONFIRM_BUTTON"
    const val VOTES_ITEMS_LAZY_COLUMN = "VOTES_ITEMS_LAZY_COLUMN"
    const val VOTES_TRY_LOAD_BUTTON = "VOTES_TRY_LOAD_BUTTON"
    const val VOTES_FAILURE_MESSAGE = "VOTES_FAILURE_MESSAGE"
    const val VOTE_ITEMS_LAZY_COLUMN = "VOTE_ITEMS_LAZY_COLUMN"
}